# Generated by Django 5.2.4 on 2025-08-06 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('url_destino', models.URLField()),
                ('imagen_qr', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('visitas', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
